### ISSUE TITLE
Problem with asynchronous functions

### ISSUE THREAD

**Issue by stephane-ruhlmann** [daspec/daspec-js#1]
Hi!

I'm having trouble testing some local API endpoints via an async call (get method from superagent npm module), the step is just ignored and the test result tells me there is "Nada in da spec".

Does not daspec support it ?

Here's my consumer-step.js file (if I run a synchronous function, everything is fine) :

```javascript
var request = require("superagent");

defineStep(/Getting on API should return (.*)/, function(expectedResponse){
    request.get("http://localhost:8080/test").end(function(err, res){
        expect(res.body.test).toEqual(expectedResponse);
    });
});
```

**Comment by gojko** [comment]
promises (async functions) are not yet supported in daspec. they should be supported soon, in v1.1

**Comment by stephane-ruhlmann** [comment]
That woud be great. Thank you.

**Comment by gojko** [comment]
v 1.1.0 supports promises - you just have to return the promise out of the step definition to make sure that the test runner waits for it to complete.
