### ISSUE TITLE
Table headers and separators sometimes included in steps

### ISSUE THREAD

**Issue by mjstrasser** [daspec/daspec-js#2]
I have created a specification containing tables where DaSpec includes table headers and separator rows in the matched steps to use. 

This simple example shows what happens with DaSpec 1.1.0.

# Output

```
> daspec
Address:  Address
Address:  -------------------------------------------
Address:  150 Lonsdale Street Melbourne Victoria
Address:  175 Liverpool Street Sydney NSW
Req address:  -------------------------------------------
Req address:  150 Lonsdale Street Melbourne Victoria
Req address:  175 Liverpool Street Sydney NSW
STATUS  EXEC    PASS    FAIL    ERR     SKIP
-----------------------------------------------------------
?       0       0       0       0       0       specs/fixed-serviceability.md
-----------------------------------------------------------
?       0       0       0       0       0       TOTAL
```

# Step definitions

```javascript
/* global defineStep, expect */

// Definition that processes the whole table in one step.
defineStep(/Given these addresses and serviceabilities:/, function(table) {
    "use strict";
    table.items.forEach(function (stubData) {
        console.log('Address: ', stubData[0]);
        // Add to stub server.
    });
});

// Match a table header row: each body row is a separate step.
defineStep(/Requested Address .* Location ID/, function(address, isServiceable, locationId) {
    "use strict";
    console.log('Req address: ', address);
    // Call service under test for this address and verify response.
});
```

# Specification

## Fixed Serviceability microservice

> This microservice is accepts an unstructured street address and checks whether
> the property at that address can have an NBN service installed.

> The service uses the [Google Maps Geocoding API](https://developers.google.com/maps/documentation/geocoding/intro)
> to find the latitude and longitude of the specified address and the NBN Domain Manager
> to check if that location can have NBN installed.
   
Given these addresses and serviceabilities:

| Address                                   | Latitude     | Longitude   | Serviceable? | Location ID |
|-------------------------------------------|--------------|-------------|--------------|-------------|
| 150 Lonsdale Street Melbourne Victoria    | -37.8105182  | 144.9656141 | true         | LOC0000150  |
| 175 Liverpool Street Sydney NSW           | -33.8771684  | 151.2082734 | false        | LOC0000175  |

## Notes

> These are actual latitudes and longitudes from Google Maps but are not real NBN DM values.
> The value *service down* means the respective service is not available to the Fixed Serviceability microservice.

## Successful requests

| Requested Address                         | Serviceable? | Location ID |
|-------------------------------------------|--------------|-------------|
| 150 Lonsdale Street Melbourne Victoria    | true         | LOC0000150  |
| 175 Liverpool Street Sydney NSW           | false        | LOC0000175  |

**Comment by gojko** [comment]
I assume it's some whitespace edge case. I just copied the thing from the comment and put it into the web site example runner, and the console log didn't contain the separators. Can you send me the actual spec file to e-mail gojko@neuri.co.uk

**Comment by mjstrasser** [comment]
I have revisited the issue and found that line-endings makes a difference. My spec file was created on Windows and had CRLF line-endings. When I changed that to LF endings the extra step matching stopped (running on Windows).

Here is the output of both specs:

```
D:\Workspace\daspec\tables>daspec
Address:  Address
Address:  -------------------------------------------
Address:  150 Lonsdale Street Melbourne Victoria
Address:  175 Liverpool Street Sydney NSW
Req address:  -------------------------------------------
Req address:  150 Lonsdale Street Melbourne Victoria
Req address:  175 Liverpool Street Sydney NSW
STATUS  EXEC    PASS    FAIL    ERR     SKIP
-----------------------------------------------------------
?       0       0       0       0       0       specs/fixed-serviceability_CRLF.md
Address:  150 Lonsdale Street Melbourne Victoria
Address:  175 Liverpool Street Sydney NSW
Req address:  150 Lonsdale Street Melbourne Victoria
Req address:  175 Liverpool Street Sydney NSW
?       0       0       0       0       0       specs/fixed-serviceability_LF.md
-----------------------------------------------------------
?       0       0       0       0       0       TOTAL
```

I have emailed you both files as well.

(BTW thanks for showing me that the daspec.com examples can be edited in Chrome. I didn’t know that because I habitually use Firefox, where they cannot be edited.)
