### ISSUE TITLE
Sometimes the wrong match group is highlighted in Markdown output

### ISSUE THREAD

**Issue by mjstrasser** [daspec/daspec-js#3]
I have a case where DaSpec 1.1.0 highlights the wrong match group in Markdown output.

# Source code

```javascript
function orderStatus(svcStatus) {
    return svcStatus;
}
```

# Step definitions
```javascript
defineStep(/Order ORD001 has status (\w+) if service SVC001 has status (\w+)/, function(ordStatus, svcStatus) {
    expect(orderStatus(svcStatus)).toEqual(ordStatus);
});
```

# Specification

> DaSpec 1.1.0 hightlights the wrong match group in some circumstances.

## Passing

> The last match group is highlighted even though the expectation is against the first one.

Order ORD001 has status COMPLETED if service SVC001 has status COMPLETED.

## Failing

> The first match group is correctly highlighted.

Order ORD001 has status COMPLETED if service SVC001 has status FAILED.

**Comment by mjstrasser** [comment]
I re-read the [page on step automation](http://daspec.com/guides/good_automation_practices.html) and found this workaround:

```javascript
defineStep(/Order ORD001 has status (\w+) if service SVC001 has status (\w+)/, function(ordStatus, svcStatus) {
    expect(orderStatus(svcStatus)).toEqual(ordStatus).atPosition(0);
});
```

**Comment by gojko** [comment]
yes, that's the correct way to do it.

**Comment by mjstrasser** [comment]
I still think it is a bug and this behaviour contravenes the documentation as I read it.

Why is the failure case different to the success case? Here is the output Markdown when `atPosition` is not called:

> **In da spec:** executed: 2, passed: 1, failed: 1

# Match group order

> DaSpec 1.1.0 highlights the wrong match group in some circumstances.

## Passing

> The last match group is highlighted even though the expectation is against the first one.

Order ORD001 has status COMPLETED if service SVC001 has status **COMPLETED**.

## Failing

> The first match group is correctly highlighted.

Order ORD001 has status **~~COMPLETED~~ [FAILED]** if service SVC001 has status FAILED.

**Comment by gojko** [comment]
I would expect this to highlight the first match group as well in the success scenario, because you're overriding it. if it's not, then it is a bug. i'll investigate more

**Comment by mjstrasser** [comment]
This issue occurs when the match groups *evaluate* to the same value (in this case **COMPLETED**). If they evaluate to different values (as in the failure case here) then the correct match group is highlighted.

Looking at the code in `expect.js`, it would be difficult to solve because the `addAssertion` function uses the passed values, not names of the match groups. It does not set `position` on the assertion and cannot do so.

It is a reasonable limitation to require that `atPosition` is called if the expected and actual values are specified to be the same.

**Comment by gojko** [comment]
Hi,

I'm not sure if I understood correctly what you expected, but I added a [test to contain your use case](https://github.com/daspec/daspec-js/commit/659b8a577c78d1298b1a319115f9a1323fcbdac3). When I run it, the correct group is highlighted both in success and failure cases. Do you get a different result?

JS doesn't have support for variable names, so we have to work on the positions. If you expect values of various match groups to be the same, then overriding the position is the best way to go.

**Comment by mjstrasser** [comment]
There is no bug. The problem was that I didn’t RTFM properly as described in my previous comment.
