### ISSUE TITLE
as a user, can I choose an assertion framework

### ISSUE THREAD

**Issue by capaj** [daspec/daspec-js#6]
I noticed that I need to use built in assertion framework. Otherwise, daspec doesn't consider a step as successful. I think daspec should consider a step as succesful if there weren't any thrown errors or if returned promise was resolved.

Would it be okay for you to consider letting users use any assertion framework? I mostly use chai.

**Comment by saufpompiers** [comment]
Hi,

this is not an option at the moment, because it's not enough to just throw an exception (how most assertion frameworks deal with errors). DaSpec needs a lot more information to render the results correctly.
